export const API_HEADER_KEYS = {
  AUTHORIZATION: 'AUTHORIZATION',
  ACCESS_TOKEN: 'ACCESS_TOKEN'
};

export const ACTION_TYPES = {
  SET_ALL_PRODUCTS: 'SET_ALL_PRODUCTS',
  ADD_TO_BASKET: 'ADD_TO_BASKET',
  REMOVER_FROM_BASKET: 'REMOVER_FROM_BASKET'
};

export const LOCAL_STORAGE_KEYS = {
  BASKET: 'BASKET'
};
